CREATE TABLE STUDENT_REGISTRATION_REQUEST (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    ENDERECO_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
);
