ALTER TABLE ENDERECO ALTER COLUMN ID RESTART WITH 4;
ALTER TABLE USUARIO ALTER COLUMN ID RESTART WITH 4;
ALTER TABLE VEICULO ALTER COLUMN ID RESTART WITH 3;
ALTER TABLE ROTA ALTER COLUMN ID RESTART WITH 3;
ALTER TABLE ALUNO ALTER COLUMN ID RESTART WITH 4;
ALTER TABLE MOTORISTA ALTER COLUMN ID RESTART WITH 3;
